In [5]:

import pandas as pd
from pathlib import Path

# Exact location of your Week 9 project
project_dir = Path(
    r"C:\Users\preet\Downloads\Week9_Chatbot_Development"
)

dataset_dir = project_dir / "dataset"

# Load sample questions
questions = pd.read_csv(
    dataset_dir / "sample_questions.csv",
    encoding="utf-8-sig"
)

print("WEEK 9 - CAMPUSAI CHATBOT DEVELOPMENT")
print("Total Sample Questions:", len(questions))

display(questions)

WEEK 9 - CAMPUSAI CHATBOT DEVELOPMENT
Total Sample Questions: 20

,Question_ID,Category,Question
0,1,Factual,What is Artificial Intelligence?
1,2,Factual,What is Machine Learning?
2,3,Factual,What is Deep Learning?
3,4,Factual,What is Natural Language Processing?
4,5,Factual,What is the difference between AI and ML?
5,6,Reasoning,Why is Python widely used in Artificial Intell...
6,7,Reasoning,How can AI improve the education system?
7,8,Reasoning,Why is data preprocessing important in Machine...
8,9,Reasoning,How does overfitting affect a Machine Learning...
9,10,Reasoning,Why do chatbots need conversation history?
10,11,Coding,Write a Python program to check whether a numb...
11,12,Coding,Write a Python program to calculate factorial ...
12,13,Coding,Explain how to reverse a string in Python.
13,14,Coding,Write a Python program to find the largest num...
14,15,Coding,Explain the difference between a list and a tu...
15,16,General Conversation,Hello CampusAI how are you?
16,17,General Conversation,Can you help me prepare for my exams?
17,18,General Conversation,What are some effective study techniques?
18,19,General Conversation,How can I improve my programming skills?
19,20,General Conversation,Thank you for helping me today.

In [6]:

# Load chatbot responses
responses = pd.read_csv(
    dataset_dir / "responses.csv",
    encoding="utf-8-sig"
)

print("CAMPUSAI - CHATBOT RESPONSE ANALYSIS")
print("Total Responses:", len(responses))

# Display question, response and status
display(
    responses[
        [
            "Question_ID",
            "Category",
            "Question",
            "Response",
            "Status"
        ]
    ]
)

CAMPUSAI - CHATBOT RESPONSE ANALYSIS
Total Responses: 20

,Question_ID,Category,Question,Response,Status
0,1,Factual,What is Artificial Intelligence?,"Okay, let's break down Artificial Intelligence...",Success
1,2,Factual,What is Machine Learning?,"Okay, let's break down what Machine Learning i...",Success
2,3,Factual,What is Deep Learning?,"Okay, let's break down Deep Learning! Here's a...",Success
3,4,Factual,What is Natural Language Processing?,"Okay, let's break down Natural Language Proces...",Success
4,5,Factual,What is the difference between AI and ML?,"Okay, let's break down the difference between ...",Success
5,6,Reasoning,Why is Python widely used in Artificial Intell...,"Okay, let’s dive into why Python is so popular...",Success
6,7,Reasoning,How can AI improve the education system?,"Okay, let’s break down how AI can dramatically...",Success
7,8,Reasoning,Why is data preprocessing important in Machine...,"Okay, let’s break down why data preprocessing ...",Success
8,9,Reasoning,How does overfitting affect a Machine Learning...,"Okay, let’s break down how overfitting affects...",Success
9,10,Reasoning,Why do chatbots need conversation history?,"Okay, let’s break down why chatbots need conve...",Success
10,11,Coding,Write a Python program to check whether a numb...,"```python\ndef is_prime(number):\n """"""\n Thi...",Success
11,12,Coding,Write a Python program to calculate factorial ...,"Okay, let's write a Python program to calculat...",Success
12,13,Coding,Explain how to reverse a string in Python.,"Okay, let’s explain how to reverse a string in...",Success
13,14,Coding,Write a Python program to find the largest num...,```python\ndef find_largest_number(numbers):\n...,Success
14,15,Coding,Explain the difference between a list and a tu...,"Okay, let's break down the difference between ...",Success
15,16,General Conversation,Hello CampusAI how are you?,"Hello there! I’m doing well, thank you for ask...",Success
16,17,General Conversation,Can you help me prepare for my exams?,"Okay, absolutely! I’d love to help you prepare...",Success
17,18,General Conversation,What are some effective study techniques?,"Okay, let’s talk about effective study techniq...",Success
18,19,General Conversation,How can I improve my programming skills?,"Okay, that’s a fantastic goal! Improving your ...",Success
19,20,General Conversation,Thank you for helping me today.,You’re very welcome! I’m glad I could help. 😊 ...,Success

In [7]:

# CampusAI chatbot performance analysis

total_questions = len(responses)

successful = (
    responses["Status"].str.strip().str.lower() == "success"
).sum()

failed = total_questions - successful

success_rate = (
    successful / total_questions * 100
    if total_questions > 0 else 0
)

average_time = responses["Response_Time_Seconds"].mean()

print("CAMPUSAI CHATBOT - PERFORMANCE REPORT")
print("------------------------------------")
print("Total Questions:", total_questions)
print("Successful Responses:", successful)
print("Failed Responses:", failed)
print(f"Success Rate: {success_rate:.2f}%")
print(f"Average Response Time: {average_time:.2f} seconds")

print("\nCATEGORY-WISE PERFORMANCE")

category_report = responses.groupby("Category").agg(
    Total_Questions=("Question_ID", "count"),
    Average_Response_Time=("Response_Time_Seconds", "mean")
)

display(category_report)

CAMPUSAI CHATBOT - PERFORMANCE REPORT
------------------------------------
Total Questions: 20
Successful Responses: 20
Failed Responses: 0
Success Rate: 100.00%
Average Response Time: 7.36 seconds

CATEGORY-WISE PERFORMANCE

                      Total_Questions  Average_Response_Time
Category
Coding                              5                  7.636
Factual                             5                  7.912
General Conversation                5                  6.216
Reasoning                           5                  7.676


## Chatbot Observations and Analysis

### 1. Testing Methodology
The CampusAI chatbot was developed using Python and Ollama with the Gemma 3 (1B) model.

The chatbot was tested using 20 education-related questions across four categories:
- Factual questions
- Reasoning questions
- Coding questions
- General conversation

Responses were recorded in responses.csv along with timestamps, execution times and status information.

### 2. Strengths
- Runs locally using Ollama.
- Supports interactive conversations through Python.
- Maintains conversation history during a chatbot session.
- Can explain educational concepts and generate Python code.
- Automatically saves conversations in CSV format.
- Records timestamps and chatbot activity for later analysis.

### 3. Limitations
- Response generation depends on available computer resources.
- The model may generate incorrect or incomplete information.
- Long conversations may exceed the model's context window.
- Conversation history is maintained in memory during execution but is not automatically restored when the program restarts.
- The chatbot does not verify answers against external educational sources.

### 4. Prompt Improvements
The chatbot uses a system prompt instructing the model to provide clear educational explanations and simple examples.

Possible improvements include:
- Adding more specific instructions for coding questions.
- Asking the model to explain reasoning step by step.
- Limiting response length for faster generation.
- Adding a mechanism to check answers against reliable sources.

### 5. Future Scope
The project can be extended using LangChain to:
- Manage conversation memory.
- Create reusable prompt templates.
- Integrate educational documents.
- Implement retrieval-augmented generation (RAG).

### 6. Conclusion
CampusAI demonstrates how a local LLM can be used to build an interactive educational chatbot.

The project implements command-line interaction, conversation history, CSV logging and automated testing. It provides a foundation for future LangChain integration.

In [8]:

# Review coding and reasoning responses
review = responses[
    responses["Category"].isin(["Coding", "Reasoning"])
]

for _, row in review.iterrows():
    print("=" * 65)
    print("Question ID:", row["Question_ID"])
    print("Category:", row["Category"])
    print("Question:", row["Question"])
    print("\nCampusAI Response:")
    print(row["Response"])
    print("\nStatus:", row["Status"])
    print()

=================================================================
Question ID: 6
Category: Reasoning
Question: Why is Python widely used in Artificial Intelligence?

CampusAI Response:
Okay, let’s dive into why Python is so popular in Artificial Intelligence (AI)! It’s a really significant reason, and it boils down to a combination of factors that make it incredibly accessible and versatile. Here’s a breakdown of the key reasons:

**1. Simple and Readable Syntax:**

* **Easier to Learn:** Python’s syntax is designed to be relatively easy to read and understand, especially for beginners. It's closer to plain English than many other programming languages.  Think of it like this: you can understand a simple sentence just as easily as you can read a complex paragraph.
* **Example:**  Instead of writing complicated code with lots of semicolons and brackets, you can write things like

Status: Success

=================================================================
Question ID: 7
Category: Reasoning
Question: How can AI improve the education system?

CampusAI Response:
Okay, let’s break down how AI can dramatically improve the education system! It’s a really exciting area with a lot of potential. Here’s a breakdown of key areas and specific examples:

**1. Personalized Learning – Tailoring to Each Student:**

* **The Problem:** Traditional education often uses a one-size-fits-all approach. Students learn at different paces and have different strengths and weaknesses.
* **AI Solution:** AI algorithms can analyze a student’s performance, learning style, and preferences to create a personalized learning path.
* **Examples:**
    * **Adaptive Learning Platforms:** Platforms like Knewton or DreamBox Learning adjust the difficulty and content based on a student’s real-time

Status: Success

=================================================================
Question ID: 8
Category: Reasoning
Question: Why is data preprocessing important in Machine Learning?

CampusAI Response:
Okay, let’s break down why data preprocessing is so crucial in machine learning. Think of it like this: your data is like ingredients for a recipe – if you don’t prepare them properly, the final product (your model) won’t turn out well.

**Here’s a breakdown of why it’s so important:**

**1. Machine Learning Models Need Clean Data:**

* **Models learn patterns:** Machine learning algorithms (like neural networks or support vector machines) *learn* from the data. They don’t magically understand the data; they need a good starting point.
* **Garbage in, garbage out:**  If your data is messy, incomplete, or inconsistent, your model will learn

Status: Success

=================================================================
Question ID: 9
Category: Reasoning
Question: How does overfitting affect a Machine Learning model?

CampusAI Response:
Okay, let’s break down how overfitting affects a machine learning model. It’s a crucial concept to understand!

**What is Overfitting?**

Simply put, overfitting is when your machine learning model learns the training data *too* well. It becomes very good at recognizing the specific examples it’s seen during training, but it struggles to generalize – to accurately predict things on *new*, unseen data.  Think of it like a student who memorizes all the answers to practice questions without actually understanding the underlying concepts.

**Here's a breakdown of how it happens:**

1. **The Training Data:**  You feed a machine learning model a large set of data (the training data) that’s specifically designed

Status: Success

=================================================================
Question ID: 10
Category: Reasoning
Question: Why do chatbots need conversation history?

CampusAI Response:
Okay, let’s break down why chatbots need conversation history – it’s a really important part of how they work! Here's a breakdown in simple terms:

**The Core Idea: Remembering What Happened**

Think of it like this: You’re having a conversation with a friend. You don't just start from scratch every time they say something new. You remember what you've already talked about, so you can respond more naturally and appropriately. Chatbots need conversation history for the same reason.

**Here's a more detailed explanation:**

1. **Context is Key:**  Chatbots are designed to understand *what* you're saying.  Without conversation history, they'd be stuck trying to

Status: Success

=================================================================
Question ID: 11
Category: Coding
Question: Write a Python program to check whether a number is prime.

CampusAI Response:
```python
def is_prime(number):
  """
  This function checks if a given number is prime.

  Args:
    number: The number to check.

  Returns:
    True if the number is prime, False otherwise.
  """
  if number <= 1:
    return False  # Numbers less than or equal to 1 are not prime
  if number <= 3:
    return True  # 2 and 3 are prime numbers

  # If divisible by 2 or 3, it's not prime
  if number % 2 == 0 or number % 3 == 0:
    return False

  # Iterate from

Status: Success

=================================================================
Question ID: 12
Category: Coding
Question: Write a Python program to calculate factorial using recursion.

CampusAI Response:
Okay, let's write a Python program to calculate the factorial of a number using recursion.

```python
def factorial_recursive(n):
  """
  Calculates the factorial of a non-negative integer using recursion.

  Args:
      n: A non-negative integer.

  Returns:
      The factorial of n.  Returns 1 if n is 0.
  """
  if n == 0:
    return 1  # Base case: factorial of 0 is 1
  else:
    return n * factorial_recursive(n-1)  # Recursive step

# Example Usage:
num = 5
result = factorial_recursive(num

Status: Success

=================================================================
Question ID: 13
Category: Coding
Question: Explain how to reverse a string in Python.

CampusAI Response:
Okay, let’s explain how to reverse a string in Python! There are several ways to do this, and I’ll cover the most common and straightforward methods.

**1. Using String Slicing (The Simplest Method)**

This is the most Pythonic and generally preferred way because it's concise and efficient.

```python
string = "Hello, World!"
reversed_string = string[::-1]
print(reversed_string)  # Output: !dlroW ,olleH
```

**Explanation:**

* **`string[::-1]`**: This is a slice of the string.  Let's break it down:
    * `string`:  This is the string you want

Status: Success

=================================================================
Question ID: 14
Category: Coding
Question: Write a Python program to find the largest number in a list.

CampusAI Response:
```python
def find_largest_number(numbers):
  """
  This function finds the largest number in a list.

  Args:
    numbers: A list of numbers.

  Returns:
    The largest number in the list.  Returns None if the list is empty.
  """
  if not numbers:  # Check if the list is empty
    return None

  largest_number = numbers[0]  # Initialize largest_number with the first element
  for number in numbers:
    if number > largest_number:
      largest_number = number
  return largest_number

# Example Usage:
numbers = [10, 5, 20

Status: Success

=================================================================
Question ID: 15
Category: Coding
Question: Explain the difference between a list and a tuple in Python.

CampusAI Response:
Okay, let's break down the difference between lists and tuples in Python. They're both ways to store collections of data, but there are key distinctions that make them suitable for different situations.

**1. Lists**

* **What they are:** Lists are *mutable*, meaning you can *change* their contents after they've been created.  Think of them like a whiteboard – you can write on it, erase it, add things to it, and remove things.
* **How they're created:** You create a list using square brackets `[]`.
* **Syntax:** `my_list = [1, 2, 3, "apple", "banana"]`
* **Key Features:**

Status: Success

In [9]:

import ollama
import pandas as pd
from datetime import datetime

model = "gemma3:1b"

prompts = {
    "Original": "Explain overfitting in Machine Learning.",
    "Improved": (
        "Explain overfitting in Machine Learning. "
        "Include a simple definition, a real-world example, "
        "its consequences, and two prevention techniques. "
        "Use clear headings and student-friendly language."
    )
}

results = []

for prompt_type, prompt in prompts.items():
    print(f"\nTesting {prompt_type} Prompt...")

    response = ollama.chat(
        model=model,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        options={
            "num_predict": 300,
            "num_ctx": 2048
        }
    )

    answer = response["message"]["content"]

    results.append({
        "Timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "Prompt_Type": prompt_type,
        "Prompt": prompt,
        "Response": answer
    })

    print("Response:")
    print(answer)
    print("-" * 60)

comparison = pd.DataFrame(results)

comparison.to_csv(
    dataset_dir / "prompt_comparison.csv",
    index=False
)

print("\nPrompt comparison saved successfully!")
display(comparison)

Testing Original Prompt...
Response:
Okay, let's break down overfitting in Machine Learning. It's a common problem that can significantly impact the performance of your models. Here’s a comprehensive explanation:

**1. What is Overfitting?**

Overfitting occurs when a machine learning model learns the *training data* too well – too much detail – instead of learning the underlying, generalizable patterns.  Essentially, it becomes too complex to accurately represent the data it was trained on.

Think of it like a student who memorizes answers to practice questions instead of understanding the concepts. They'll ace the practice tests but struggle when faced with new, slightly different questions.

**2. How Does It Happen?**

* **Complex Models:** Overfitting is often linked to using models that are more complex than necessary.  This can be due to:
    * **Too many features:** Including irrelevant or redundant features.
    * **High-degree polynomials:** In linear models, high-degree polynomials can lead to overfitting.
    * **Deep Neural Networks:**  Deep networks can easily memorize the training data, particularly if the data is very noisy.
* **Training Data Specificity:** The model focuses too closely on the specific quirks and noise within the training set, rather than the generalizable rules.
* **Lack of Regularization:**  Regularization techniques are designed to prevent overfitting by adding a penalty to the model’s complexity.


**3.  Symptoms of
------------------------------------------------------------

Testing Improved Prompt...
Response:
Okay, let’s break down overfitting in Machine Learning!

**What is Overfitting?**

Imagine you're teaching a student to recognize cats. You show them *only* pictures of fluffy, orange cats.  The student becomes *so* good at recognizing orange cats that they start noticing *everything* about those orange cats – the pattern of the fur, the color of the eyes, even the slight curve of the nose – that they start to focus on *those specific details* instead of the core characteristics that truly define a cat.  They might even start recognizing *other* animals as cats! That’s overfitting.

In Machine Learning, **overfitting** happens when a model learns the *training data* too well – it becomes too complex and captures all the noise and irrelevant details within that data. It performs *exceptionally* well on the data it was trained on, but performs poorly on new, unseen data (data it hasn’t been shown during training).  It’s like a student memorizing facts instead of understanding the big picture.


**Real-World Example: Predicting House Prices**

Let's say you're building a machine learning model to predict house prices based on features like square footage, number of bedrooms, location, and age.

* **Training Data:** You give the model a dataset of 100 houses with their actual sale prices.
* **Overfitting Scenario:** The model, because it memorized
------------------------------------------------------------

Prompt comparison saved successfully!

,Timestamp,Prompt_Type,Prompt,Response
0,2026-10-29 20:38:04,Original,Explain overfitting in Machine Learning.,"Okay, let's break down overfitting in Machine ..."
1,2026-10-29 20:38:20,Improved,Explain overfitting in Machine Learning. Inclu...,"Okay, let’s break down overfitting in Machine ..."